"""
core/report_generator.py
==========================
Renders a scenario run (and its enriched events) into a shareable HTML
report, and optionally converts that HTML to PDF with WeasyPrint. This
powers the "HTML/PDF Report Generator" dashboard module.
"""
import uuid
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, BaseLoader
from sqlalchemy.orm import Session

from app.config import get_settings
from app.models.event import Event
from app.models.scenario_run import ScenarioRun

TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>PurpleLab AI Report - {{ run.scenario_name }}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #0b0f19; color: #e5e7eb; margin: 0; padding: 32px; }
  h1 { color: #a78bfa; margin-bottom: 4px; }
  .meta { color: #9ca3af; font-size: 14px; margin-bottom: 24px; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; }
  .status-completed { background: #14532d; color: #86efac; }
  .status-failed { background: #7f1d1d; color: #fca5a5; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #1f2937; font-size: 13px; vertical-align: top; }
  th { color: #a78bfa; text-transform: uppercase; font-size: 11px; letter-spacing: .05em; }
  .sev-critical { color: #f87171; font-weight: 700; }
  .sev-high { color: #fb923c; font-weight: 700; }
  .sev-medium { color: #facc15; }
  .sev-low, .sev-info { color: #9ca3af; }
  .technique { color: #60a5fa; font-family: monospace; }
  .section-title { margin-top: 32px; color: #a78bfa; }
  .footer { margin-top: 40px; font-size: 11px; color: #6b7280; }
</style>
</head>
<body>
  <h1>PurpleLab AI - Purple Team Exercise Report</h1>
  <div class="meta">
    Scenario: <strong>{{ run.scenario_name }}</strong> &middot;
    Target: {{ run.target_host }} &middot;
    Status: <span class="badge status-{{ run.status.value if run.status.value else run.status }}">{{ run.status.value if run.status.value else run.status }}</span><br/>
    Started: {{ run.started_at }} &middot; Finished: {{ run.finished_at or '—' }}<br/>
    Generated: {{ generated_at }}
  </div>

  <h2 class="section-title">Event Timeline</h2>
  <table>
    <thead>
      <tr><th>Time</th><th>Source</th><th>Actor</th><th>Action</th><th>Severity</th><th>MITRE Technique</th></tr>
    </thead>
    <tbody>
      {% for e in events %}
      <tr>
        <td>{{ e.timestamp }}</td>
        <td>{{ e.source }}</td>
        <td>{{ e.actor or '—' }}</td>
        <td>{{ e.action }}</td>
        <td class="sev-{{ e.severity }}">{{ e.severity }}</td>
        <td class="technique">{{ e.mitre_technique_id or '—' }} {{ e.mitre_technique_name or '' }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <h2 class="section-title">AI Copilot Analysis</h2>
  {% for e in events %}
    {% if e.ai_explanation %}
    <div style="margin-bottom:18px; padding:12px; background:#111827; border-left:3px solid #a78bfa; border-radius:6px;">
      <strong>{{ e.action }}</strong> <span class="technique">({{ e.mitre_technique_id or 'unmapped' }})</span>
      <p style="margin:8px 0;">{{ e.ai_explanation }}</p>
      <p style="margin:4px 0; color:#93c5fd;"><strong>Detection:</strong><br/>{{ e.detection_guidance }}</p>
      <p style="margin:4px 0; color:#86efac;"><strong>Mitigation:</strong><br/>{{ e.mitigation_guidance }}</p>
    </div>
    {% endif %}
  {% endfor %}

  <div class="footer">
    Generated by PurpleLab AI for authorized, isolated lab use only. This report documents
    activity performed against a lab virtual machine under the user's own control.
  </div>
</body>
</html>
"""


def _render_html(run: ScenarioRun, events: list[Event]) -> str:
    env = Environment(loader=BaseLoader())
    template = env.from_string(TEMPLATE)
    return template.render(run=run, events=events, generated_at=datetime.utcnow().isoformat())


def generate_html_report(db: Session, run: ScenarioRun) -> Path:
    events = db.query(Event).filter(Event.run_id == run.id).order_by(Event.timestamp).all()
    html = _render_html(run, events)
    settings = get_settings()
    out_path = settings.reports_path / f"report_{run.scenario_key}_{uuid.uuid4().hex[:8]}.html"
    out_path.write_text(html, encoding="utf-8")
    return out_path


def generate_pdf_report(db: Session, run: ScenarioRun) -> Path:
    events = db.query(Event).filter(Event.run_id == run.id).order_by(Event.timestamp).all()
    html = _render_html(run, events)
    settings = get_settings()
    out_path = settings.reports_path / f"report_{run.scenario_key}_{uuid.uuid4().hex[:8]}.pdf"
    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(str(out_path))
    except Exception as exc:  # pragma: no cover - optional system deps (pango/cairo) may be missing
        raise RuntimeError(
            "PDF generation requires WeasyPrint's system libraries (pango, cairo, gdk-pixbuf). "
            f"Install them per the README, or use the HTML report instead. Original error: {exc}"
        )
    return out_path
